# Generated by Django 6.0.6 on 2026-06-17 09:37

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import ops.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('blueprint_url', models.URLField(blank=True, null=True)),
                ('unit_weight', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatrixShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('FRACTIONED', 'Fracionado'), ('RETURNED', 'Retornado')], default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentFactory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry_code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corporate_name', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('prefecture', models.CharField(blank=True, max_length=100)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', ops.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MatrixShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_expected', models.IntegerField()),
                ('global_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.globalpart')),
                ('matrix_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.matrixshipment')),
                ('tenant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='matrixshipment',
            name='parent_factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.parentfactory'),
        ),
        migrations.AddField(
            model_name='globalpart',
            name='parent_factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.parentfactory'),
        ),
        migrations.CreateModel(
            name='ReusableQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('tenant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parentfactory',
            name='tenant_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant'),
        ),
        migrations.AddField(
            model_name='matrixshipment',
            name='tenant_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant'),
        ),
        migrations.AddField(
            model_name='globalpart',
            name='tenant_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovementLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('MATRIZ_IN', 'Entrada da Matriz'), ('WORKER_DISTRIBUTION', 'Saída para Trabalhador'), ('WORKER_RETURN_APPROVED', 'Retorno Trabalhador (Aprovado)'), ('WORKER_RETURN_REFUSE', 'Retorno Trabalhador (Refugado)'), ('LOSS_DIVIDEND', 'Perda Física / Dividendo'), ('MATRIZ_RETURN', 'Retorno para a Matriz')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.globalpart')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaishokuJobOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incremental_id', models.IntegerField(blank=True, null=True)),
                ('short_audit_code', models.CharField(max_length=100)),
                ('quantity_assigned', models.IntegerField()),
                ('payout_per_unit', models.DecimalField(decimal_places=1, max_digits=10)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Alocado'), ('IN_PRODUCTION', 'Em Produção'), ('READY_DELIVERING', 'Pronto para Entrega'), ('READY_PICKUP', 'Pronto para Coleta'), ('COLLECTING', 'Coletando'), ('IN_INSPECTION', 'Em Inspeção'), ('FINALIZED', 'Finalizado')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField()),
                ('deadline', models.DateField()),
                ('quantity_approved', models.IntegerField(default=0)),
                ('quantity_refused', models.IntegerField(default=0)),
                ('quantity_lost', models.IntegerField(default=0)),
                ('matrix_shipment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.matrixshipmentitem')),
                ('reusable_qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.reusableqrcode')),
                ('tenant_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='ops.tenant')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
