# Generated by Django 6.0.6 on 2026-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpart',
            name='blueprint_file',
            field=models.FileField(blank=True, null=True, upload_to='blueprints/'),
        ),
        migrations.AddField(
            model_name='globalpart',
            name='part_photo',
            field=models.FileField(blank=True, null=True, upload_to='part_photos/'),
        ),
        migrations.AlterField(
            model_name='globalpart',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
