# Generated by Django 6.0.6 on 2026-06-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_globalpart_blueprint_file_globalpart_part_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='longitude',
        ),
        migrations.AddField(
            model_name='worker',
            name='geolocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
